name: Quality
# description:
# - Runs ktlint providing source code quality and review information
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'gradle.properties'
      - 'LICENSE'
      - 'README.md'

jobs:
  quality:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Create release')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ktlint
        uses: vroy/gha-kotlin-linter@v1
