name: release

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/build.yml
      - .github/workflows/codeql.yml
      - .github/workflows/release.yml
      - .gitignore
      - gradle.properties
      - LICENSE
      - README.md

jobs:
  release:
    uses: opengood-aio/central-workflows/.github/workflows/gradle-plugin-release.yml@main
    with:
      git-email: ${{ vars.GIT_EMAIL }}
      git-user: ${{ vars.GIT_USER }}
      run-gradle-validation: true
    secrets:
      gradle-publish-key: ${{ secrets.GRADLE_PUBLISH_KEY }}
      gradle-publish-secret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      workflow-token: ${{ secrets.WORKFLOW_TOKEN }}
